### ISSUE TITLE
Installing inside Godot Editor - multiple entries

### ISSUE THREAD

**Issue by temzky** [Maulve/onscreen-output#4]
When I search "Onscreen Output" inside Godot Editor 4 identical entries show up. How am I supposed to pick the right one? The fault is probably on Godot Editor side - it should show only the newest compatible version - but you can workaround this by putting the Godot version in the addon title.
![godot-issue](https://github.com/user-attachments/assets/53a8ea47-4348-4c3c-a902-b6bc85f74481)

**Comment by Maulve** [comment]
This will (hopefully) soon be resolved.
I will remove at least the bottom-right one (v0.9), as it's redundant, and instead of making new uploads just edit the old ones.

I might also remove some of the other versions, but I have yet to decide that.

**Comment by Maulve** [comment]
Resolved by deleting all but one entry.
2.0 is currently pending on that entry.
